config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
    devise_for :admins, controllers: {
    sessions: 'devise/sessions',
    passwords: 'devise/passwords',
    registrations: 'devise/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get "about" => "homes#about", as: :about
  get "/:current_customers/my_page" => "customers#show", as: :my_page
  get "/:current_customers/edit" => "customers#edit", as: :edit_customer
  get "/:current_customers/check" => "customers#check", as: :check
  get "/order_addresses" => "addresses#index", as: :addresses
  post "/order_addresses" => "addresses#create"
  get "/order_addresses/:id/edit" => "addresses#edit", as: :edit_address
  patch "/order_addresses/:id/edit" => "addresses#update"
  delete "/order_addresses/:id" => "addresses#destroy", as: :destroy_address
  
  
  resources :items, only: [:index, :show]
  resources :admins
  resources :customers, only: [:index, :show, :update]
  resources :order_details, only: [:index, :show, :edit, :update]
  resources :cart_items, only: [:create, :index, :edit, :destroy, :update]
  
  namespace :admin do
      resources :items, only: [:new, :index, :create, :show, :edit, :update]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :customers, only: [:index, :show, :edit, :update]
      resources :orders, only: [:show, :update]
      resources :order_details, only: [:update]
      root to: 'homes#top'
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def full_name
    last_name + first_name
  end
  
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  attachment :image
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
    enum status: {
    "入金待ち": 0,
    "入金確認": 1,
    "製作中": 2,
    "発送準備中": 3,
    "発送済み": 4
  }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    
      enum status: {
    "製作不可": 0,
    "製作待ち": 1,
    "製作中": 2,
    "完成": 3,
  }
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @address = Address.new
    addresses = Address.all
    @addresses = current_customer.addresses
  end
  
  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @address.save
    redirect_to addresses_path
  end
  
  def edit
    @address = Address.find(params[:id])
  end
  
  def update
    @address = Address.find(params[:id])
    @address.update(address_params)
    redirect_to addresses_path
  end
  
  def destroy
    address = Address.find(params[:id])
    address.destroy
    redirect_to addresses_path
  end
  
  private
  
  def address_params
    params.require(:address).permit(:name, :postal_code, :address, :customer_id)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  
  def index
    cart_items = CartItem.all
    @cart_items = current_customer.cart_items
  end
  
  def update
    @cart_item = CartItem.find(params[:id])
    @cart_item.update(cart_item_params)
    redirect_to cart_items_path
  end
  
  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    @cart_item.save
    redirect_to cart_items_path
  end
  
  def destroy
    cart_item = CartItem.find(params[:id])
    cart_item.destroy
    redirect_to cart_items_path
  end
  
  private
  
  def cart_item_params
    params.require(:cart_item).permit(:amount, :customer_id, :item_id)
  end
  
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  
  def show
    @customer = Customer.find(current_customer[:id])
  end
  
  def edit
    @customer = Customer.find(current_customer[:id])
  end
  
  def update
    @customer = Customer.find(current_customer[:id])
    @customer.update(customer_params)
    redirect_to customer_path(current_customer.id)
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active)
  end
  
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :image, :price, :is_active, :genre_id)
  end
  
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
 <div class="row">
  <h3 class="col-sm-3 bg-secondary text-center mt-5 mb-5">ジャンル編集</h3>
 </div>
</div>

<div class="container">
  <div class="row">
   <table class="col-sm-6">
    <%= form_with model: [:admin, @genre], local:true do |f| %>
     <tr>
      <th>ジャンル名</th>
      <th><%= f.text_field :name %></th>

      <th>
       <div><%= f.submit '変更を保存', class: "btn btn-success btn-block" %></div>
      </th>
     </tr>
    <% end %>
   </table>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
 <div class="row">
  <h3 class="col-sm-3 bg-secondary text-center mt-5 mb-5">ジャンル一覧・追加</h3>
 </div>
</div>

<div class="container">
  <div class="row">
   <table class="col-sm-6">
    <%= form_with model: [:admin, @genre], local:true do |f| %>
     <tr>
      <th>ジャンル名</th>
      <th><%= f.text_field :name %></th>
      <th>
       <div><%= f.submit '新規登録', class: "btn btn-success btn-block" %></div>
      </th>
     </tr>
    <% end %>
   </table>
  </div>
</div>

<div class="container">
  <div class="row">
   <div class="col-sm-4">
    <table class="table">
     <thead>
      <tr>ジャンル</tr>
     </thead>
    
     <tbody>
      <% @genres.each do |genre| %>
       <tr>
        <th><%= genre.name %></th>
        <th><%= link_to "編集する", edit_admin_genre_path(genre.id) %></th>
       </tr>
      <% end %>
     </tbody>
    </table>
   </div>
  </div>
 </div>

app/views/genres/edit.html.erb
<div class="container">
 <div class="row">
  <h3 class="col-sm-3 bg-secondary text-center mt-5 mb-5">ジャンル編集</h3>
 </div>
</div>

<div class="container">
  <div class="row">
   <table class="col-sm-6">
    <%= form_with model:@genre, local:true do |f| %>
     <tr>
      <th>ジャンル名</th>
      <th><%= f.text_field :name %></th>

      <th><%= f.submit '変更を保存', class: "btn btn-success btn-block" %></th>
     </tr>
    <% end %>
   </table>
  </div>
</div>

app/views/genres/index.html.erb
<div class="container">
 <div class="row">
  <h3 class="col-sm-3 bg-secondary text-center mt-5 mb-5">ジャンル一覧・追加</h3>
 </div>
</div>

<div class="container">
  <div class="row">
   <table class="col-sm-6">
    <%= form_with model:@genre, local:true do |f| %>
     <tr>
      <th>ジャンル名</th>
      <th><%= f.text_field :name %></th>
      <th><%= f.submit '新規登録', class: "btn btn-success btn-block" %></th>
     </tr>
    <% end %>
   </table>
  </div>
</div>

<div class="container">
  <div class="row">
   <div class="col-sm-4">
    <table class="table">
     <thead>
      <tr>ジャンル</tr>
     </thead>
    
     <tbody>
      <% @genres.each do |genre| %>
       <tr>
        <th><%= genre.name %></th>
        <th><%= link_to "編集する", edit_genre_path(genre.id) %></th>
       </tr>
      <% end %>
     </tbody>
    </table>
   </div>
  </div>
 </div>