config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
    devise_for :admins, controllers: {
    sessions: 'devise/sessions',
    passwords: 'devise/passwords',
    registrations: 'devise/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get "about" => "homes#about", as: :about
  get "/:current_customers/my_page" => "customers#show", as: :my_page
  get "/:current_customers/edit" => "customers#edit", as: :edit_customer
  get "/:current_customers/check" => "customers#check", as: :check
  get "/order_addresses" => "addresses#index", as: :addresses
  post "/order_addresses" => "addresses#create"
  get "/order_addresses/:id/edit" => "addresses#edit", as: :edit_address
  patch "/order_addresses/:id/edit" => "addresses#update"
  delete "/order_addresses/:id" => "addresses#destroy", as: :destroy_address
  
  
  resources :items, only: [:index, :show]
  resources :admins
  resources :customers, only: [:index, :show, :update]
  resources :order_details, only: [:index, :show, :edit, :update]
  resources :cart_items, only: [:create, :index, :edit, :destroy, :update]
  
  namespace :admin do
      resources :items, only: [:new, :index, :create, :show, :edit, :update]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :customers, only: [:index, :show, :edit, :update]
      resources :orders, only: [:show, :update]
      resources :order_details, only: [:update]
      root to: 'homes#top'
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def full_name
    last_name + first_name
  end
  
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  attachment :image
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  
    enum status: {
    "入金待ち": 0,
    "入金確認": 1,
    "製作中": 2,
    "発送準備中": 3,
    "発送済み": 4
  }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :item
    
      enum status: {
    "製作不可": 0,
    "製作待ち": 1,
    "製作中": 2,
    "完成": 3,
  }
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @items = Item.all
  end
  
  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end
  
  private
  
  def item_params
    params.require(:item).permit(:name, :introduction, :image, :price, :is_active, :genre_id)
  end
  
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
     <nav class="navbar navbar-light">
       <div class="container">
         <div class="navbar-brand p-3">nagano_cake</div>
         <% if admin_signed_in? %>
           <li class="nav-item">
             <%= link_to "商品一覧", admin_items_path %>
           </li>
      
           <li class="nav-item">
             <%= link_to "会員一覧", admin_customers_path %>
           </li>
      
           <li class="nav-item">
             <%= link_to "注文履歴一覧", order_details_path %>
           </li>
      
           <li class="nav-item">
             <%= link_to "ジャンル一覧", admin_genres_path %>
           </li>
      
           <li class="nav-item">
             <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
           </li>
         <% elsif customer_signed_in? %>
           <li class="nav-item">
             <%= link_to "マイページ", my_page_path(current_customer.id) %>
           </li>
      
           <li class="nav-item">
             <%= link_to "商品一覧", items_path %>
           </li>
      
           <li class="nav-item">
             <%= link_to "カート", order_details_path %>
           </li>
      
           <li class="nav-item">
             <%= link_to "ジャンル一覧" %>
           </li>
      
           <li class="nav-item">
             <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
           </li>
         <% else %>
       　   <li class="nav-item">
             <%= link_to "About", about_path %>
           </li>
           <li class="nav-item">
             <%= link_to "商品一覧" %>
           </li>
           <li class="nav-item">
             <%= link_to "新規登録", new_customer_registration_path %>
           </li>
           <li class="nav-item">
             <%= link_to "ログイン", new_admin_session_path %>
           </li>
         <% end %>
       </div>
     </nav>
   </header>
   <%= yield %>
  </body>
</html>